services:
  - type: web
    name: jogo-server
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run build && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

  - type: static
    name: jogo-client
    staticPublishPath: ./client/dist
    buildCommand: cd client && npm install && npm run build
    routes:
      - path: /
        index: index.html
      - path: /*
        index: index.html
