services:
  - type: web
    name: jogo-multiplayer
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run build && npm run start
    envVars:
      - key: NODE_ENV
        value: production
