services:
  - type: web
    name: jogo-multiplayer
    runtime: node
    plan: free
    buildCommand: npm install && npm run build:prod
    startCommand: node server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
